### ISSUE TITLE
lmeep_mpi-default and bg_phanom_2d.bin

### ISSUE THREAD

**Issue by ChengxiaoWang** [RI-imaging/FDTD_sinogram#2]
Hello,

I am testing your code by "python series_angle.py" and I just want to get the result as yours in "examples". But there are 2 errors:
error1: "/usr/bin/ld: cannot find -lmeep_mpi-default"    
error2: "execvp error on file bg_phantom_2d.bin (No such file or directory)"
I have installed meep by "sudo apt-get install libmeep-mpi-default-dev libmeep-mpi-default17".
And I think something stopped the generation of "file bg_phantom_2d.bin", so I can't find it in directory.

Is there any solution？

Thanks a lot！

**Comment by paulmueller** [comment]
Hi @ChengxiaoWang,

looks like you are having an issue installing MEEP. Please take a look at the docs https://meep.readthedocs.io/en/latest/Installation/ and ask for help in the MEEP community.
