### ISSUE TITLE
Visualization of the 3D refractive index phantom for the FDTD simulations

### ISSUE THREAD

**Issue by ChengxiaoWang** [RI-imaging/FDTD_sinogram#3]
Hello,

I noticed in your paper "ODTbrain: a Python library for full-view, dense diffraction tomography", there is a short video about the visualization of the 3D refractive index phantom for the FDTD simulations in Additional file 2.
So how do you get the visualization? by program or another code?

Thanks a lot!

**Comment by paulmueller** [comment]
Hello, as far as I remember, I used https://docs.enthought.com/mayavi/mayavi/.
